config/routes.rb
SearchlightDemo::Application.routes.draw do
  root controller: "books", action: "home"
  get "/without_searchlight", controller: "books", action: "without_searchlight"
  get "/searchlight_activerecord", controller: "books", action: "searchlight_activerecord"
  get "/searchlight_sequel", controller: "books", action: "searchlight_sequel"
  mount SinatraSearchlight => "/sinatra_searchlight"
end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :books

  validates :first_name, :last_name, presence: true
  validates_uniqueness_of :last_name, scope: :first_name

  scope :name_like, -> name { where("concat(authors.first_name, ' ', authors.last_name) ILIKE ?", "%#{name}%") }

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category

  validates :title, :author, :category, presence: true
  validates_uniqueness_of :title, scope: [:author_id, :category_id]
  scope :title_like, -> (title) { where("books.title ILIKE ?", "%#{title}%") }
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, uniqueness: true
end

app/models/sequel/author.rb
module Sequel
  class Author < Sequel::Model
    plugin :validation_helpers

    one_to_many :books

    def validate
      super
      validates_presence [:first_name, :last_name]
      validates_unique [:first_name, :last_name]
    end

    dataset_module do
      def name_like(name)
        where(
          Sequel.join([:first_name, :last_name], ' ').ilike("%#{name}%")
        )
      end
    end 

  end
end

app/models/sequel/book.rb
module Sequel
  class Book < Sequel::Model
    plugin :validation_helpers

    many_to_one :author
    many_to_one :category

    def validate
      super
      validates_presence [:author, :category, :title]
      validates_unique [:title, :author_id, :category_id]
    end
    
    dataset_module do
      def title_like(title)
        where(Sequel.ilike(:title, "%#{title}%"))
      end
    end 
  end
end

app/models/sequel/category.rb
module Sequel
  class Category < Sequel::Model
    plugin :validation_helpers

    one_to_many :books

    def validate
      super
      validates_presence :name
      validates_unique :name
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def home
  end

  def searchlight_activerecord
    @search = BookSearch.new(search_params)
    @books  = @search.results
  end

  def searchlight_sequel
    @search = Sequel::BookSearch.new(search_params)
    @books  = @search.results.all
  end

  def without_searchlight
    @books = Book.all.order("title ASC")

    if search_params[:title_like].present?
      @books = @books.merge(Book.title_like(search_params[:title_like]))
    end

    if search_params[:author_name_like].present?
      @books = @books.joins(:author).merge(Author.name_like(search_params[:author_name_like]))
    end

    if search_params[:category_in].present? && search_params[:category_in].any?(&:present?)
      @books = @books.where(category_id: search_params.fetch(:category_in).select {|v| v.present? })
    end

    if search_params[:author_also_wrote_in_category_id].present? && search_params[:author_also_wrote_in_category_id].any?(&:present?)
      query_string = <<-YE_OLDE_QUERY_LANGUAGE.strip_heredoc
      INNER JOIN authors                        ON books.author_id         = authors.id
      INNER JOIN books      AS other_books      ON other_books.author_id   = authors.id
      INNER JOIN categories AS other_categories ON other_books.category_id = other_categories.id
      YE_OLDE_QUERY_LANGUAGE
      @books = @books.joins(query_string).where("other_categories.id = ?", search_params[:author_also_wrote_in_category_id])
    end

    if search_params[:board_book].present?
      @books = @books.where(board_book: search_params[:board_book])
    end

    search_params[:in_print] ||= "either"
    unless search_params[:in_print].to_s == "either"
      @books = @books.where(in_print: search_params[:in_print])
    end
  end

  protected

  def search_params
    @search_params ||= params.delete(:book_search) || params.delete(:sequel_book_search) || {}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_link(text, path)
    link_to text, path, class: "#{'active' if current_page?(path)}"
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper

  def categories_collection
    @categories_collection ||= Category.all.map {|cat| [cat.name, cat.id] }
  end

end

app/views/books/_search_form.html.haml
= form_for @search, url: root_path, remote: remote_opt, method: :get do |f|
  %fieldset
    = f.label      :title_like
    = f.text_field :title_like

  %fieldset
    = f.label      :author_name_like
    = f.text_field :author_name_like

  %fieldset
    = f.label   :category_id
    = f.select  :category_id, categories_collection, include_blank: true

  %fieldset
    = f.label   :author_also_wrote_in_category_id
    = f.select  :author_also_wrote_in_category_id, categories_collection, include_blank: true

  %fieldset
    = f.label   :board_book
    = f.check_box  :board_book

  %fieldset
    = f.label   :in_print
    = f.select  :in_print, [["Yes", true], ["No", false], ["Either", "either"]]

  %button{type: :reset} Clear
  = f.submit 'Search'

app/views/books/_search_results.html.haml
- if @books.any?
  %table
    %thead
      %th Category Name
      %th Author First Name
      %th Author Last Name
      %th Title
      %th Board Book?
      %th In Print?
    %tbody
      - @books.each do |book|
        %tr
          %td= book.category.name
          %td= book.author.first_name
          %td= book.author.last_name
          %td= book.title
          %td= book.board_book ? "Yes" : "No"
          %td= book.in_print ? "Yes" : "No"
- else
  Sadly, there are no matching books as of #{I18n.l(Time.current)}.

app/views/books/_searchlight_form.html.haml
= form_for @search, url: url, method: :get do |f|

  %fieldset
    = f.label      :title_like
    = f.text_field :title_like

  %fieldset
    = f.label      :author_name_like
    = f.text_field :author_name_like

  %fieldset
    = f.label   :category_in
    = f.select  :category_in, categories_collection, {include_blank: true}, multiple: true

  %fieldset
    = f.label   :author_also_wrote_in_category_id
    = f.select  :author_also_wrote_in_category_id, categories_collection, include_blank: true

  %fieldset
    = f.label   :board_book
    = f.check_box  :board_book

  %fieldset
    = f.label   :in_print
    = f.select  :in_print, [["Yes", true], ["No", false], ["Either", "either"]]

  %button{type: :reset} Clear
  = f.submit 'Search'

app/views/books/_without_searchlight_form.html.haml
= form_tag url, method: :get do

  = fields_for :book_search do |f|

    %fieldset
      = f.label      :title_like
      = f.text_field :title_like, value: @search_params[:title_like]

    %fieldset
      = f.label      :author_name_like
      = f.text_field :author_name_like, value: @search_params[:author_name_like]

    %fieldset
      = f.label   :category_in
      = f.select  :category_in, categories_collection, {include_blank: true, selected: @search_params[:category_in]}, multiple: true 

    %fieldset
      = f.label   :author_also_wrote_in_category_id
      = f.select  :author_also_wrote_in_category_id, categories_collection, include_blank: true, selected: @search_params[:author_also_wrote_in_category_id]

    %fieldset
      = f.label   :board_book
      = f.check_box  :board_book, checked: @search_params[:board_book] == "1"

    %fieldset
      = f.label   :in_print
      = f.select  :in_print, [["Yes", true], ["No", false], ["Either", "either"]], selected: @search_params[:in_print]


    %button{type: :reset} Clear
    = f.submit 'Search'

app/views/books/home.html.haml
%h1 Searchlight Demo App

:markdown
  This is a demo of [the Searchlight Ruby gem](https://github.com/nathanl/searchlight). There are three versions of the search above - which will you choose?

  Oh, I'm kidding, choose all of them! They should all work **exactly the same**. Only the code is different - the [controller code](https://github.com/nathanl/searchlight_demo/blob/master/app/controllers/books_controller.rb) and the [view code](https://github.com/nathanl/searchlight_demo/tree/master/app/views/books).

  The goal is for you to see that 1) searching with Searchlight is nicer than doing all the parameter parsing and setting of defaults in your controller and 2) Searchlight works with more than one ORM.

- content_for :footer do
  %span
    -# nothing! :) (footer is redundant here)

app/views/books/searchlight_activerecord.html.haml
%h1 Searchlight + ActiveRecord

= render 'searchlight_form', search: @search, url: searchlight_activerecord_path

%h2 Book Results

#book_search_results
  = render 'search_results'

app/views/books/searchlight_sequel.html.haml
%h1 Searchlight + Sequel

= render 'searchlight_form', search: @search, url: searchlight_sequel_path

%h2 Book Results

#book_search_results
  = render 'search_results'

app/views/books/without_searchlight.html.haml
%h1 Without Searchlight

= render 'without_searchlight_form', search: @search, url: without_searchlight_path

%h2 Book Results

#book_search_results
  = render 'search_results'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Searchlight Demos
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %header
      %nav
        %ul
          %li= menu_link "Home", root_path
          %li= menu_link "Without Searchlight", without_searchlight_path
          %li= menu_link "Searchlight + ActiveRecord", searchlight_activerecord_path
          %li= menu_link "Searchlight + Sequel", searchlight_sequel_path

    %main
      = yield

    %footer
      - if content_for?(:footer)
        = yield(:footer)
      - else
        #links
          %p
            :markdown
              A demo of [the Searchlight Ruby gem](https://github.com/nathanl/searchlight). Demo code is viewable at [https://github.com/nathanl/searchlight_demo](https://github.com/nathanl/searchlight_demo).